name: template
description: Template package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  data_table_2: 2.5.15
  multiple_search_selection: ^2.7.0
  intl: ^0.19.0
  intl_utils: ^2.7.0
  animated_custom_dropdown: 3.1.1
  flutter_fancy_tree_view: ^1.6.0
  crypto: ^3.0.6
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  dotted_border: ^2.1.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  video_player: 2.9.2
  chewie: ^1.3.5
  syncfusion_flutter_charts: ^28.1.37
  random_string: ^2.3.1
  visibility_detector: ^0.4.0+2
  animated_tree_view: ^2.3.0
  equatable: ^2.0.5
  dio: ^5.4.0
  tab_container: ^3.5.3
  photo_view: ^0.15.0
  get_it: ^7.6.4
  calendar_date_picker2: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true